# Generated by Django 6.0.1 on 2026-01-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='Category')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('discountPercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Discount Percentage')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rating')),
                ('stock', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Stock')),
                ('brand', models.CharField(blank=True, max_length=15, null=True, verbose_name='Brand')),
                ('sku', models.CharField(blank=True, max_length=20, null=True, verbose_name='SKU')),
                ('weight', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Weight')),
                ('warrantyInformation', models.CharField(blank=True, max_length=25, null=True, verbose_name='Warranty Information')),
                ('shippingInformation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shipping Information')),
                ('availabilityStatus', models.CharField(blank=True, max_length=10, null=True, verbose_name='Availability Information')),
                ('returnPolicy', models.CharField(blank=True, max_length=25, null=True, verbose_name='Return Policy')),
                ('minimumOrderQuantity', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Minimum Order Quantity')),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True, verbose_name='Thumbnail')),
            ],
        ),
    ]
