# Generated by Django 6.0.1 on 2026-01-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Salary'),
        ),
    ]
