# Generated by Django 6.0.1 on 2026-01-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employee_join_date_alter_employee_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Monthly Salary'),
        ),
    ]
