# Generated by Django 6.0.1 on 2026-01-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_employee_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, max_length=15, null=True, verbose_name='Join Date'),
        ),
    ]
