# Generated by Django 6.0.1 on 2026-01-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_employee_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Salary'),
        ),
    ]
