# Generated by Django 6.0.1 on 2026-01-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=10, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(blank=True, max_length=10, null=True, verbose_name='Last Name')),
                ('maidenName', models.CharField(blank=True, max_length=10, null=True, verbose_name='Maiden Name')),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Age')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('username', models.CharField(blank=True, max_length=10, null=True, verbose_name='User Name')),
                ('password', models.CharField(blank=True, max_length=10, null=True, verbose_name='Password')),
                ('birthDate', models.DateField(blank=True, max_length=15, null=True, verbose_name='Birth Date')),
                ('bloodGroup', models.CharField(blank=True, max_length=5, null=True, verbose_name='Blood Group')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Height')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Weight')),
                ('eyeColor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Eye Color')),
                ('role', models.CharField(blank=True, max_length=10, null=True, verbose_name='Role')),
            ],
        ),
    ]
