# Generated by Django 6.0.1 on 2026-01-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Age'),
        ),
    ]
