# Generated by Django 6.0.1 on 2026-01-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Age'),
        ),
    ]
